app:
  build: .
  command: uvicorn app:app --host 0.0.0.0 --port 8008
  ports:
    - "8008:8008"
  links:
    - db
db:
  image: mongo:latest
  hostname: scraping_mongodb
  environment:
    - MONGO_INITDB_DATABASE=fb_scraping
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=pass
  ports:
    - 27000:27017